### ISSUE TITLE
"Current directory not indexed" when src-root not in /var/opengrok

### ISSUE THREAD

**Issue by ohle** [asenac/vim-opengrok#1]
When the current directory is an indexed project that does not reside in /var/opengrok, find_index_root_dir will fail, and consequently so will all plugin commands.

**Comment by asenac** [comment]
Hi,

vim-opengrok was designed to use its own per-project index directory, which is stored within a .opengrok directory within the root directory of the project, generated with opengrok's command line tools. However,  we could add something to support that use case, where the index is shared between opengrok's web app and vim-opengrok.

I would need to investigate this further, but I think it could be something like using an optional setting variable to indicate where the configuration.xml file is stored. It would be something like:

```
aug OpengrokStuff
    au!
    au BufRead,BufNew /path/to/my/proyect/* let g:og_configuration_file = '/var/opengrok/etc/configuration.xml'
aug END
```

Actually, we could even fall back to /var/opengrok/etc/configuration.xml if find_index_root_dir returns nothing.

Would that work for you?

I think I can check that in later today.

**Comment by ohle** [comment]
Ah, I completely misinterpreted that, then. Sorry.

The advantage of using an index managed outside of the plugin would be that reindexing could be done with cron jobs, like for the webapp, so I think it would be nice to have. For the moment I'd also be fine with with the current solution.

You might, however, consider to add a hint about running `:OgIndex` to the error message.

**Comment by asenac** [comment]
Good idea. Will do. I will also write a first version of the documentation with the basic workflow.

**Comment by asenac** [comment]
Just added a new option to use an external index. You just need to define in your vimrc where the configuration.xml file of the index is, by doing:

```
let g:opengrok_config_file = '/var/opengrok/etc/configuration.xml'
```
